# openapi2-functions.yaml
swagger: '2.0'
info:
  title: some-api1 optional-string
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://us-central1-api-project-630491316919.cloudfunctions.net/cheepenary
      responses:
        '200':
          description: A successful response
          schema:
            type: string